### ISSUE TITLE
Tasks to do

### ISSUE THREAD

**Issue by jtquach1** [CS-410/pl-fshack-infant#1]
# Tasks outlined by 3/29/2021 video
- [x] Set up the cookie cutter plugin and rename it to pl-infant-fshack
- [x] Copy over all the [pl-fshack](https://github.com/FNNDSC/pl-fshack) files to that cookie cutter plugin
- [x] Change the Dockerfile
- [ ] Run pl-fshack-infant
- [ ] Build and upload the Docker image to Docker Hub
- [ ] Write an infantfshack.sh based off of [RedHatSummit2018.sh](https://github.com/FNNDSC/CHRIS_docs/blob/master/workflows/RedHatSummit2018.sh)
- [ ] Create [JSON representation](https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Quickstart#6-register-your-plugin) of plugin to upload to ChRIS store

# Tasks outlined by 3/10/2021 video
- [ ] Read [Quickstart](https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Quickstart) 

# Miscellaneous tasks (may have to clarify with client)
- [x] ... and do step 5 to build and push a container image
  - We'll have to make a Docker image at some point
- [ ] Do step 6 and register the plugin
- [ ] Make a Docker Hub account [here](https://hub.docker.com/signup)
  - This is so whenever any of us push changes to this repo, the Docker image for this plugin gets updated.

# How to set up Docker Hub account
1. Go to [Linked Accounts](https://hub.docker.com/settings/linked-accounts)
2. Connect your GitHub account
~~3. Join [cs410](https://hub.docker.com/orgs/cs410) on Docker Hub~~
3. View Docker Hub images
  - So it looks like everyone can push changes to the repo, it's just that only 3 people can build and push to Docker Hub

**Comment by szmei** [comment]
### To Do Before Next Meeting:

- [ ]  shell script:
    - [ ] input dataset
- [ ] uploading the plugin to Chris backend making sure it runs probably
        
- [ ]  javascript:
    - [ ]  connect to cube API
###
